server:
  port: 7071
  address: 
spring:
   boot:
     admin:
        client: 
           url: http://localhost:9999
   application:
    name: JRTP701ISH-ApplicationRegistrationService
   config:
      import: optional:configserver:http://localhost:8888 

#property for register with eureka server
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
   


ar: 
    ssa-web:
       url: http://localhost:9090/ssa-web-api/find/{ssn}
    state: california
    
    
        
#activate all the actuators
management:
   endpoint:
      env:
         enabled: true
         show-values: always
      health:
         show-details: always
   endpoints:
      web:
            exposure:
                include: '*'