server:
  port: 7074
spring:
  boot:
     admin:
        client: 
           url: http://localhost:9999
  application:
    name: JRTP701ISH-Admin-API
  config:
      import: optional:configserver:http://localhost:8888 

#property for register with eureka server
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
         
         
         
#activate all the actuators
management:
   endpoint:
      env:
         enabled: true
         show-values: always
      health:
         show-details: always
   endpoints:
      web:
            exposure:
                include: '*'
         
    
plan:
   module:
      message:
         save-success: Plan is saved with id value
         save-failure: Plan is not saved with id value
         update-success: Plan is updated
         update-failure: Plan is not found for updation
         find-by-id-failure: Plan is not found
         delete-success: Plan is deleted
         delete-failure: Plan is not found for deletion
         status-change-success: Plan Status is changed
         status-change-failure: Plan is not found for status change